name: Publish Docker Image & Deploy to Remote Server

on:
  push:
    branches: [master]
  release:
    types: [created] # 表示在创建新的 Release 时触发

jobs:
  build_docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/buptreasure-server:${{ steps.date.outputs.today }}
            ${{ secrets.DOCKER_USERNAME }}/buptreasure-server:latest
  deploy:
    name: Deploy to Remote Server
    needs: build_docker
    runs-on: ubuntu-20.04
    steps:
      - name: Change Docker socket permissions
        run: sudo chmod 666 /var/run/docker.sock
      - name: Deploy to Remote Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SUDO_PASSWORD }}
          key: ${{ secrets.PR_KEY }}
          script: |
            docker stop buptreasure-server-temp
            docker rmi acs991314/buptreasure-server:latest
            docker pull acs991314/buptreasure-server:latest
            docker rm buptreasure-server-temp
            docker run --name buptreasure-server-temp -p 9000:8080 --net bupt-net -v /home/nginx/html/temp:/app/buffer -d acs991314/buptreasure-server:latest